---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clucle
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clucle
  template:
    metadata:
      labels:
        app: clucle
    spec:
      containers:
      - name: clucle
        image: clucle/web
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: MONGODB_HOSTNAME
          value: mongodb-0.mongodb-headless.database
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_DATABASE
          value: clucle-web
        - name: MONGODB_USERNAME
          value: clucle
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: creds
              key: db-password
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
